DROP DATABASE IF EXISTS parking;
CREATE DATABASE parking;
USE parking;

CREATE TABLE AVAILABLE_SPOTS (
		ID INT PRIMARY KEY AUTO_INCREMENT,
		PARKSPOTS INT
);
INSERT INTO AVAILABLE_SPOTS (PARKSPOTS) VALUES (0);