# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: TestBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.14
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./backend/requirements.txt
    - name: Test with unittest
      run: |
        python3 run_tests.py
      env:
        SECURE_URL: ${{ secrets.SECURE_URL }}
